laravel/telescope

- src/Http/Controllers/MonitoredTagController.php
- src/IncomingDumpEntry.php
- `assignEntryPointFromBatch()` does not return anything
- `store()` and `destroy()` do not return anything
> [1.0] update docblocks

- readme.md
telescope will not work on 5.7 installs earlier than 5.7.7
> [1.0] update Laravel requirement

- composer.json
Use PHP `^7.1.3`, as it's sufficient to get any Laravel 5.7 app running.
See https://github.com/laravel/laravel/blob/master/composer.json#L8
> [1.0] Use PHP ^7.1.3

- composer.json
many files in telescope use JSON functions, so we'll make sure we require the extension
> [1.0] require JSON extension

- src/Watchers/RedisWatcher.php
`implode()` requires an array passed as the second parameter.
> [1.0] fix docblock

- src/Http/Controllers/MonitoredTagController.php
- src/IncomingDumpEntry.php
- src/Telescope.php
consistent with everywhere else
also fix the order of one docblock @param
> [1.0] use fully qualified class names in docblocks

- src/Watchers/RequestWatcher.php
method can return either an array or a string
> [1.0] fix return type

- src/Http/Controllers/RouterController.php
- src/Http/routes.php
Right now you can't run `route:cache` because of closure.
> [1.0] Fix route caching

- composer.json
- phpstan.neon.dist
- src/ListensForStorageOpportunities.php
- src/Storage/DatabaseEntriesRepository.php
- src/Telescope.php
This Pull Request adds [nunomaduro/larastan](http://github.com/nunomaduro/larastan) as `require-dev` dependency of Telescope. Larastan is a wrapper of PHPStan, and is a **static analysis** tool for PHP.
About Phpstan: "_PHPStan is a static analysis tool for PHP code. It parses your code and tries to find flaws in the program logic (like a variable being used before being declared, or a function being called that does not exist...). It is not the ultimate tool for catching bugs but it has one huge advantage: it does not need a lot work to set up! No need to write unit tests, simply run the tool and it will output a list of potential errors!_".
You can read more in this article: [medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3](https://medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3)
This …
> [1.0] Adds Larastan

- composer.json
- added "laravel/framework" : "^5.7.7", to `required`, since laravel should be with minimum version v5.7.7.
So after this commit composer will update automaticly laravel to 5.7.7 or package will not be installed;
Similar to https://github.com/laravel/telescope/pull/45
> [1.0] Added `laravel/framework` to dependency

- resources/js/components/IndexScreen.vue
- resources/js/components/PreviewScreen.vue
- resources/js/screens/dumps/index.vue
- resources/js/screens/monitoring/index.vue
- resources/views/layout.blade.php
while *mostly* valid, self closing `<path>` tags are not valid in **all** browsers and flavors of HTML.
switching for more inclusive compatibility.
> [1.0] use closing tag for `<path>`

- src/EntryResult.php
- Changed `DateTimeInterface` to `Carbon\Carbon` in `EntryResult`, since in `jsonSerialize` we have used `$this->createdAt->toDateTimeString()`.
toDateTimeString method not exist in `DateTimeInterface` but present on Carbon
> [1.0] Changed `DateTimeInterface` to `Carbon\Carbon` in `EntryResult`.

- mix-manifest.json
- resources/views/layout.blade.php
- webpack.mix.js
Hi,
Lets version the assets same as horizon
https://github.com/laravel/horizon/blob/4b4822fa7dc8ec69842a339b44fe73d0a63f1cc7/resources/views/app.blade.php#L6
I have removed the `mix-manifest.json` from root. It will be generated inside `public` folder from now.
I have not complied the assets, they should be complied before new release.
> [1.0] Version assets

- src/Watchers/NotificationWatcher.php
currently if you are running Telescope and send an anonymous notification it will error out because `AnonymousNotifiable` cannot be converted into a string.  this commit accounts for that scenario and returns a string with all of the different routes imploded together.
> [1.0] account for anonymous notifications

- resources/views/layout.blade.php
this makes the MD view much better, and the XS and SM views a *little* better.
once Bootstrap 4.2 comes out we'll be able to take advantage of `container-xl`, which will give us a fluid container until the XL breakpoint, which means a little more width on smaller screens.
> [1.0] update responsive columns

- src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php
The migrations are executed on the default DB connection instead of the one provided in the telescope config file.
Fixes #91
> [1.0] Use the database connection from the config

- src/Watchers/CommandWatcher.php
currently if you run `php artisan` with no arguments, the default `list` command is run. however, the watcher gets sent an empty string. this change gets the command name from the `getArguments()` method, and falls back to 'default', just in case for some reason that doesn't exist.
maybe this should be fixed upstream at some point, but thought I'd get this fix pushed out first before digging into the framework.
> [1.0] update `CommandWatcher`

- src/IncomingEntry.php
As a continuation of https://github.com/laravel/telescope/issues/138 @themsaid fixed one of the calls on https://github.com/laravel/telescope/commit/2bf5b122e364a57f3da1cba3809b178d7f798f38 but this one was left behind.
> Authenticatable interface does not have getKey()

- src/Telescope.php
Fixes issue #101, as no one should ever need to inspect horizon requests (can't comment on Laravel Horizon Contribs)
Having it open query's the API every couple of seconds or so
The other option is that this can be placed in the Service Provider stub file, can re-submit if need be
> Removing Horizon Routes by default

- .travis.yaml
- tests/FeatureTestCase.php
- tests/Watchers/CommandWatcherTest.php
- tests/Watchers/EventWatcherTest.php
- tests/Watchers/QueryWatcherTest.php
- Added Travis CI basic file
- Added Event Watcher simple test
- Removed `prepareDatabase` in favor of flushing Telescope entries for each test.
- Added Command Watcher test
Somebody with write access to the repository would need to setup Travis integration.
> [Coverage] Add EventWatcherTest and CommandWatcherTest

- src/Storage/EntryModel.php
- src/Storage/factories/EntryModelFactory.php
- tests/Storage/DatabaseEntriesRepositoryTest.php
While working on a test for the `DatabaseEntriesRepository::find` method, I wrote the `EntryModelFactory` and noticed that the field `uuid` was not working. It turns out that when performing an insert with Eloquent, if the model has `incrementing` set to `true` it will automatically use the `LAST_INSERTED_ID()` to set into the `keyName()` field. I fixed that by setting the `incrementing` to `false` so the correct `uuid` would stay in place.
> [Test Coverage] Add test for DatabaseEntriesRepository::find

- src/Http/routes.php
Hi,
I'm using this pattern on my apps and it broke telescope : 
`Route::pattern('id', '\d+');`
Since telescope use uuid wich should be matched by : 
`Route::pattern('uuid', '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}');`
> Use uuid for uuid

- resources/js/components/PreviewScreen.vue
- resources/js/screens/queries/preview.vue
This makes it so the PreviewScreen component emits a ready event when it is ready. Other components (currently the query preview screen) can listen for it to know when the child component is ready. This is more reliable and better for the user experience than waiting an arbitrary amount of time, after which the child component might not be ready.
> Emit ready event from PreviewScreen

- src/Console/InstallCommand.php
Tested against a new Laravel Installation, all works fine
* Essentially carries over the `file_put_contents` method to the Service Provider as well.
* Replaces the namespace using the DetectsApplicationNamespace trait
> Fixes Custom Namespacing Issues (#186)

- src/Console/PruneCommand.php
- src/TelescopeServiceProvider.php
- tests/Console/PruneCommandTest.php
Similar to #255, instead of relying on the wrong interface and checking for method existence, we can just bind the interface into the container and rely on the correct interface.
> TestCase to cover Prune command

- tests/Watchers/QueryWatcherTest.php
The test on https://travis-ci.org/laravel/telescope/jobs/448360991 failed because it took longer than 0.1 second to run a database query. That was not an actual failure but rather a lack of speed on the CPU that executed the test.
This Pull Request increases from 0.1 to 0.2 seconds the configuration for slow query in order to try and avoid more false positives.
> [1.0] Increase Query Watcher slow query settings

- src/Console/ClearCommand.php
- src/TelescopeServiceProvider.php
The ClearCommand relies on the `EntriesRepository` contract, which does not offer the method `clear()`. Moreover, if the developer tries to swap the `ClearableRepository` on the container, it will not take effect on the ClearCommand.
This pull request fixes the contract that ClearCommand uses so it can be correctly swapped.
> [1.0] Fix ClearCommand contract

- resources/views/layout.blade.php
I encountered this problem while trying to run Laravel telescope in a subdirectory (e.g localhost/laravel/public/telescope). Apparently, the assets are being called from the root directory (/), not from the public path.
Install Laravel in a subdirectory:
```
cd /var/www/ # or whatever your root directory is
laravel new telescope-test
cd telescope-test
php artisan key:generate
composer require laravel/telescope --dev
php artisan telescope:install
php artisan migrate
```
You should see this:
If we use the asset function to get the asset URL with mix, the full URL will be called, and then we should see this:
> Fix: Assets not loading when Laravel is installed in a subdirectory

- config/telescope.php
- src/Watchers/RequestWatcher.php
This PR fixes #166 and #228. Large response payloads currently throw an SQL exception due to the size exceeding the `content` column's max length and due to this exception, entries for all watchers are missed. 
This PR purges response payloads beyond a size limit that can be specified as an option to the `RequestWatcher`. This is a non-breaking change.
> fixed request watcher overflow for large response payloads

- src/Telescope.php
All config options in Laravel are snake_cased, there's no reason why this one should be camelCased. I left support for the old casing to ensure backwards compatibility.
Imho this option should also be added to the default config file, but I didn't want to invest time now to come up with a comment of exactly three lines, each one three characters shorter than the other. 😀
> Snake case config option

- src/Console/PublishCommand.php
- src/TelescopeServiceProvider.php
This PR adds a command to update Telescope assets. Currently, there is no way to do so as the `php artisan telescope:install` command does not overwrite telescope assets.
Fixes #308
> Added command to update/publish Telescope assets

- src/Http/routes.php
- tests/Http/RouteTest.php
Allows applications to add the Telescope base url by a named route.
Should the config `telescope.path` be changed, then the named route would automatically be updated. As currently this either needs to be manually defined or built from the `telescope.path` config in the parent application. 
Navigation paths often use the named routes to build the url links, this would allow a Telescope navigation path to be defined by a named route.
> Add named route for Telescope

- public/app.js
- public/mix-manifest.json
- resources/js/screens/requests/preview.vue
- src/Watchers/RequestWatcher.php
- tests/Watchers/RequestWatchersTest.php
This PR adds the following request metadata to the detail screen:
1. Controller and action
2. Middleware
3. Request duration (in ms)
Fixes #314 and fixes #265. Here's how the screen looks like:
> Add request metadata: controller, action, middleware, duration

- src/Telescope.php
Currently there is no way to filter batches of entries. For example, say we need to record all entries for an app lifecycle that result in an exception (e.g. the queries fired, the request, etc.).
This PR fixes #318 and adds the ability to filter batches like so:
```php
Telescope::filterBatch(function ($entries) {
return $entries->contains(function($entry) {
return $entry->isReportableException();
});
}
```
The above code enables us to record all entries for any app lifecycle that results in a reportable exception. If this is merged, I think we should also change the `TelescopeServiceProvider.stub` to add this as an example.
On a side note, I saw many methods in `Telescope.php` that `return new static`. I don't know if this serves any purpose. Perhaps we should delete that and just have …
> Add ability to filter batches of entries

- src/Telescope.php
- src/Watchers/RequestWatcher.php
- tests/Watchers/RequestWatchersTest.php
We'll need to be able to hide the user Authorization Token as well
> Add capacity to hide headers as well as parameters on RequestWatcher

- readme.md
We got bitten a bit by this (`telescope_entries` growing at a rate of 10GB/day due to the large stacktraces it can store), I figured we might warn others that pruning the content is a wise idea. :-)
> Add documentation about pruning the older entries to reduce disk space

- src/Telescope.php
Currently, the watchers are registered and listen to events (and store entries in memory) even on ignored commands or routes. This PR improves Telescope performance by only registering watchers & events on approved commands/routes.
> [1.0] Improve performance: dont register watchers on ignored commands / routes

- src/Telescope.php
This PR adds the ability to add ignored routes. Although this could be done with `Telescope::filter`, adding it to config is better performance due to #368.
I haven't changed the config file due to the comment conventions (both `ignore_commands` and `ignore_routes` are currently missing in `config/telescope.php`). I can take a go at it as a separate PR once (if) this is merged.
> [1.0] Add ability to ignore routes with better performance

- src/Storage/DatabaseEntriesRepository.php
- src/Telescope.php
This fixes https://github.com/laravel/telescope/issues/289
The problem was the query to collect monitored tags is called while recording the first entry in Telescope, and if you're recording a modal creation for example; that tags query will run between `INSERT` and PDO's `lastInsertId` causing the Model to have a `0` id.
> Load monitored tags early in the lifecycle

- stubs/TelescopeServiceProvider.stub
Resubmission of #369, hiding params moved to `TelescopeServiceProvider` stub and applied on non-local environments.
> [1.0] Hide security critical params and headers

- src/Watchers/RequestWatcher.php
This PR fixes https://github.com/laravel/telescope/issues/377
We'll iterate over file uploads and display a placeholder instead of trying to use the actual file.
> Format file uploads while recording a request

- src/Watchers/RequestWatcher.php
- tests/Watchers/RequestWatchersTest.php
this **PR** , resolves #387 , as i found that the problem happens when the file get unliked and when using [Spatie/Media library this line cause the problem](https://github.com/spatie/laravel-medialibrary/blob/master/src/FileAdder/FileAdder.php#L308)
so the solution makes sure that the file is uploaded succesfully using ```isValid()``` and make sure that the file exist using [PHP ```isFile()```](http://php.net/manual/en/splfileinfo.isfile.php) method
> [1.0] Fix unliked uploaded files for request watcher

- src/TelescopeServiceProvider.php
The database migrations should only be loaded when telescope is running with the database driver to avoid that we create tables that are not needed.
> [1.0] Only register migrations for database driver

- resources/views/layout.blade.php
Using single quotes on the style sheet link tag causes problems when used with beyondcode/laravel-tag-helper -package (see https://github.com/beyondcode/laravel-tag-helper/issues/9). 
To get around this issue, this change swaps those single quotes for doubles. All the other tags have double quotes so this also makes the style more consistent.
> Use double quotes for HTML attributes.

- src/Console/PruneCommand.php
- tests/Console/PruneCommandTest.php
The prune command is currently broken and tests are failing because of the `argument` call for the option. This PR fixes the hours option.
Closes #403
> [1.0] Fix prune command hours option

- resources/js/routes.js
I wanted to add processed `app.js` here but it was somehow being created with more file size on my computer. Not sure why. Maybe you should do it to keep it small.
> Correct route name for mail

- resources/js/components/IndexScreen.vue
Text overflows if the content is big in the column.
Row overflows
----
Adds horizontal bar below the table by adding `table-responsive` class.
Thanks.
> Make index table responsive

- config/telescope.php
- src/Watchers/QueryWatcher.php
When Eloquent models use third-party Composer packages to build queries, the query watcher can log class / line number location for a file outside of the Laravel `app/` or `resources/views` subdirectories.
Example Composer packages:
* https://packagist.org/packages/spatie/laravel-translatable
* https://packagist.org/packages/dimsav/laravel-translatable
* https://packagist.org/packages/staudenmeir/eloquent-eager-limit
~Example configuration:~ Changed in a comment below to `['ignore_packages' => true]`.
```php
Watchers\QueryWatcher::class => [
'enabled' => env('TELESCOPE_QUERY_WATCHER', true),
'ignore_packages' => [
'dimsav/laravel-translatable',
],
'slow' => 100,
],
```
In addition to ignoring `vendor/laravel/*`, this will also ignore `vendor/dimsav/laravel-translatable` file paths (or …
> QueryWatcher location can ignore Composer packages

- src/Storage/DatabaseEntriesRepository.php
- src/Telescope.php
- src/Watchers/CacheWatcher.php
- src/Watchers/CommandWatcher.php
- src/Watchers/DumpWatcher.php
- src/Watchers/EventWatcher.php
- src/Watchers/ExceptionWatcher.php
- src/Watchers/JobWatcher.php
- src/Watchers/LogWatcher.php
- src/Watchers/MailWatcher.php
- src/Watchers/ModelWatcher.php
- src/Watchers/NotificationWatcher.php
- src/Watchers/QueryWatcher.php
- src/Watchers/RedisWatcher.php
- src/Watchers/RequestWatcher.php
- src/Watchers/ScheduleWatcher.php
This PR will stop Telescope from building records if it's not recording anything.
Before this PR telescope was building the entries, but doesn't record them.
After this PR telescope will not even build the entries, and thus avoid any un-needed CPU usage.
> Dont build records if not recording

- resources/js/screens/requests/index.vue
I find it very useful to see the duration of a request when looking at the list. And since this information is already stored and easy to access, I think it would be useful to include it in the list
> added "Duration" column to Requests tab

- src/Watchers/ModelWatcher.php
- tests/Watchers/ModelWatcherTest.php
This PR adds the ability to specify specific model events to watch. So, say we only wanted to watch the created and updated events, we could specify the configuration of the ModelWatcher like so:
```php
ModelWatcher::class => [
'enabled' => true,
'events' => ['eloquent.created*', 'eloquent.updated*'],
],
```
Also, there are some libraries like [Laravel-Pivot](https://github.com/fico7489/laravel-pivot) that fire custom events and that creates issues such as #351. This PR fixes #351 and other such issues as we can now specify specific events to listen to, and they can exclude the custom events fired by the library. This is not a breaking change.
> [1.0] Add ability to watch specific model events

- src/RegistersWatchers.php
Removing duplicate `config` call as this check already exists in the `Telescope::start` method. So, the if block is unreachable.
> [1.0] Remove duplicate config call

- src/Telescope.php
- tests/Telescope/TelescopeTest.php
This pull request adds a `afterRecording` hook on Telescope. This will allow the developer to do whatever he/she wants when Telescope makes a new Entry. There could be lots of possibilities since the callback allows the developer to implement any logic desired.
The driver for this pull request for me is a long-running background process that does too many things.
I would still like to be able to record everything that the background job is doing for later analyzes. However, the background process can run for up to 30 minutes and can perform millions of actions.
With an `afterRecording` hook, I can monitor Telescope and force it to store and flush after each 20'000 records. This will free up memory and avoid building up more entries than the Insert Query can handle.
> [1.0] Provide AfterRecording Hook

- src/Watchers/JobWatcher.php
The recent optimization commit was causing the JobWatcher to crash when not recording. This PR fixes #475.
> [1.0] Fix job watcher crash

- config/telescope.php
- public/app.js
- public/mix-manifest.json
- resources/js/components/RelatedEntries.vue
- resources/js/mixins/entriesStyles.js
- resources/js/routes.js
- resources/js/screens/gates/index.vue
- resources/js/screens/gates/preview.vue
- resources/views/layout.blade.php
- src/EntryType.php
- src/Http/Controllers/GatesController.php
- src/Http/routes.php
- src/Telescope.php
- src/Watchers/FetchesStackTrace.php
- src/Watchers/GateWatcher.php
- src/Watchers/QueryWatcher.php
- tests/Watchers/GateWatcherTest.php
This PR adds a Gate Watcher that allows us to record and monitor gate checks. I think this would be really helpful to understand which gate/permission checks are performed on requests and the result of those checks. The Gate Watcher is disabled by default to avoid breaking changes. Closes #472.
Screenshots below:
**Index Screen**
**Preview Screen (1/2)**
**Preview Screen (2/2)**
**Related Entries on Request Screen**
> [1.0] Add Gate watcher to record gate checks

- src/Http/Controllers/EntryController.php
This PR Fixes the following bugs.
> ```ini
> TELESCOPE_QUERY_WATCHER=false
> ```
> ![image](https://user-images.githubusercontent.com/1296540/49598059-2801a180-f9c1-11e8-8ea1-9f2d7e692337.png)
> ![image](https://user-images.githubusercontent.com/1296540/49597999-04d6f200-f9c1-11e8-97b9-1143cbf80f46.png)
If config is an Array, **always** `false` condition.
Then return `'enabled'` status.
```php
$ artisan tinker
>>> config('telescope.watchers.Laravel\Telescope\Watchers\QueryWatcher', false)
=> [
"enabled" => false,
"ignore_packages" => true,
"slow" => 100,
]
>>> ! config('telescope.watchers.Laravel\Telescope\Watchers\QueryWatcher', false)
=> false
```
https://github.com/laravel/telescope/blob/54ccd6ac175f081ed2a491c48592d1ad9f1332d9/config/telescope.php#L100-L104 …
> Conditional branching in array case

- src/Watchers/GateWatcher.php
- `$user` parameter in `recordGateCheck` method can be a null
> [1.0] Update phpDoc

- src/Watchers/LogWatcher.php
- tests/Watchers/LogWatcherTest.php
Currently if we log data that has the `exception` key it will throw an exception.
So this:
```
$logger->error("Some message", [
'exception' => 'Some error message'
]);
```
will throw an error: `get_class() expects parameter 1 to be object, string given`
at: `Watchers/ExceptionWatcher.php:40)`
I've added a test to prove the bug.
And the fix: also checking if the 'exception' key is an instance of Exception.
> Fix Log watcher with exception key

- src/Telescope.php
- src/TelescopeServiceProvider.php
Before this Pull Request, it was not possible to publish the default migrations or easily ignore the migrations for the Laravel Telescope package.
If you consider these changes, users will be able to export the migrations using:
```
php artisan vendor:publish --tag=telescope-migrations
```
Users will also be able to ignore the running of these default migrations, should they wish to by calling the `Telescope::ignoreMigrations()` method in the register method of their AppServiceProvider.
These changes I have made, are only mimicking the behaviour of publishing and ignoring migrations, which is present in Laravel Passport.
Resolves https://github.com/laravel/telescope/issues/525
A pull request has also been made to the [Laravel Docs repository](https://github.com/laravel/docs/pull/4902)
> Database migrations customisation

- src/ExtractTags.php
- tests/Telescope/ExtractTagTest.php
Solution to Issue #504.
**Problem:**
In _ExtractTags_, when calling the public `fromArray` method, or the private `modelsFor` method they are both looking for either instances of `Model` or `EloquentCollection`. If an `EloquentCollection` is detected, the assumption it is made that this is the result of a query and a Collection of `Model` classes.
If however you take the result of a query and issue a `groupBy` to the Collection, it becomes a Collection of Collections, and the assumption that _$value->all()_ will resolve into an array of `Model` classes falls apart resulting in an exception thrown when _FormatModel::given_ is called.
**Solution:**
Instead of simply calling _$value->all()_, call a new method that will recurse through the collection and return a flat array containing any …
> ExtractTags from multi-level Collections

- src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php
I encountered an issue with Telescope when logging requests with large `Cache` payloads. The requests would not show up in the dashboard. When using a longer field-type for the content the request was logged as it should.
> Make longer content entries possible

- resources/js/components/Alert.vue
The svg tag is no longer used in the template, so this PR removes the CSS code targeting svg.
> [1.0] Remove unused CSS code

- config/telescope.php
- src/TelescopeServiceProvider.php
Currently there's no way to specify the domain of Telescope, and we only have the `path` option, I wanted Telescope to have its dedicated sub-domain like `telescope.myapp.com`.
Also added notes in the config comment blocks
> Add ability to configure route domain setting

- resources/js/screens/cache/preview.vue
- src/Watchers/CacheWatcher.php
I'm not sure if it's a bug, so submitting it to `master`.
> Update Cache to use seconds instead of minutes starting from Laravel 5.8

- src/Console/InstallCommand.php
Fixes a bug introduced after #558.
When registering the Telescope service provider the install command attempts to find and replace code with a needle that contains the platform's native end of line symbol, rather than what's currently being used in the file. This can result in the needle not being found on operating systems like Windows, if using Unix LF (like for PSR-2).
Fixes #271, Fixes #470, Fixes #500, Fixes #555
> Fix config newline

- tests/Watchers/DumpWatcherTest.php
- tests/Watchers/EventWatcherTest.php
- tests/Watchers/MailWatcherTest.php
- tests/Watchers/NotificationWatcherTest.php
The `assertArraySubset` method has been deprecated and the `assertContains` method should no longer be used with strings.
This alternatives suppress those warnings.
Before:
After:
> Fix PHPUnit 8 warnings

- config/telescope.php
- src/Storage/DatabaseEntriesRepository.php
- src/TelescopeServiceProvider.php
The PR introduces a new `chunk_size` configuration parameter for the `database` storage driver in order to fix the issue explained in #614.
In case someone created a custom version of the `TelescopeServiceProvider` which does not pass the new `$chunkSize` parameter to the database repository, the repository will still work due to the old default being used. Also users relying on the default service provider will have no issues as the old default is used if no configured chunk size is being found.
What I'm not sure about is how to properly document the setting. Personally, I'd prefer if there was a thorough explanation in `config/telescope.php`. There isn't really a common way to document nested configuration options though. Alternatively, we can also add it to the official documentation. …
> Make chunk size of database storage driver configurable

- src/ListensForStorageOpportunities.php
[This fix](https://github.com/laravel/telescope/commit/9dfb1b08d3cf30adcfd44c79b5aaaa1f2fe34379) did not completely solve #412.
After dispatching an event with `ShouldBroadcastNow` the following entries are not correctly associated with the current request. 
This PR solves this and disables the premature storing if an event with the sync driver was emitted.
> fix events with ShouldBroadcastNow

- composer.json
moontoast/math has bcmath as a dependency. Since phpseclib/bcmath_compat "provides" ext-bcmath, via it's composer.json, I believe this PR should eliminate bcmath as a dependency.
For good measure I've also submitted a PR to moontoast/math (https://github.com/moontoast/math/pull/11) but given that the last commit was over 5 years ago I'm not going to hold my breath on the PR even being looked at, let alone being merged in.
> rm bcmath dependency

- resources/views/layout.blade.php
We have a few project and every project has telescope. We have place the telescope monitor on a screen with a switch between all the telescopes but we now can't see witch telescope it is.
We think this is a good solution.
> Add app_name in dashboard

- resources/js/screens/models/index.vue
Before this PR, Model column truncate content from 80th character in the model screen. And show icon moves out of table. 
With this PR fix this issue changing truncate content from 70th character.
> Change model column content length

- resources/js/components/PreviewScreen.vue
Gravatar by default convert e-mail to lower case
Gravatar [examples](https://gravatar.com/site/implement/images/php/)
```php
md5('Igor@Finag.in') != md5('igor@finag.in')
```
> Convert e-mail for gravatar to lower case

- src/Watchers/RequestWatcher.php
In order to improve performance, we have customized the Laravel entry, our new entry is only initialized once at startup, not initialized in subsequent requests. 
And we used the variable [REQUEST_TIME_FLOAT](https://www.php.net/manual/en/reserved.variables.server.php) to record the start time of request. At this time, Telescope cannot calculate the time.
> Support duration calculation without constant LARAVEL_START

- src/Storage/DatabaseEntriesRepository.php
This PR is a follow-up of #615 which was a fix for SQL Server issues with large transactions where a lot of Telescope entries were created (explanation of issue in #614).
In the previous PR, I only fixed `DatabaseEntriesRepository::store($entries)` as it resolved my issues. Unfortunately, with some changes and new features a new issue came up with storage of tags in `storeTags($results)`. The solution is analogous to the previous PR and I also updated `storeExceptions($exceptions)` while being at it.
On a site note: I extracted some counting logic of `storeExceptions($exceptions)` into its own method to simplify the logic a bit. If this change is not desired, I will remove it. It is fully backwards-compatible though.
> Chunk storage of exceptions and tags

- resources/js/screens/cache/index.vue
- resources/js/screens/commands/index.vue
- resources/js/screens/events/index.vue
- resources/js/screens/exceptions/index.vue
- resources/js/screens/gates/index.vue
- resources/js/screens/jobs/index.vue
- resources/js/screens/logs/index.vue
- resources/js/screens/mail/index.vue
- resources/js/screens/models/index.vue
- resources/js/screens/notifications/index.vue
- resources/js/screens/queries/index.vue
- resources/js/screens/redis/index.vue
- resources/js/screens/requests/index.vue
- resources/js/screens/schedule/index.vue
Allows you to view the full timestamp of a resource on hover. This is useful if you're trying to figure out the exact time of a request and don't want to go into the full resource page or if you're trying to figure out the time between two requests that are old and dont want to go into the full resource page.
> Full timestamp on hover

- src/TelescopeServiceProvider.php
Currently, disabling telescope through the `TELESCOPE_ENABLED` environment variable will prevent `Telescope::start` from running but does not prevent telescope from registering routes, migrations, views etc. in the `TelescopeServiceProvider->boot` method.  
This can cause unexpected errors and problems in situations like a testing environment where telescope is disabled and the migrations are not expected to be registered.
> wrap service provider boot code in telescope.enabled conditional

- src/Http/routes.php
Right now when anybody chooses to disband the usage of Class Aliases the package will break because the `Route` alias can't be found, this can be easily fixed by importing the facade properly.
> Import Route facade in routes.php

- src/Http/Controllers/DumpController.php
I think both methods do the same actually, but according to the API/TypeHint `addSecond` doesn't take an argument.
> Typo in addSeconds

- resources/js/screens/dumps/index.vue
- src/Http/Controllers/DumpController.php
This shuld fix #682 and partially fix #611 (or at least give the user some information about it).
Addition could be to specify a cache driver in config/telescope, so that the Telescope driver could be different (eg. if you want to work with the array driver locally).
This shows an error when something goes wrong (eg. the wrong cache driver in this instance).
It also changes the loading of entries to check 1 entry and only load the rest when something changed (just like the rest of the Index screens).
> Optimize dump

- phpunit.xml.dist
As dump relies on the cache working, changed the cache to `file`
> Fix Dump test using file cache

- src/IncomingEntry.php
- stubs/TelescopeServiceProvider.stub
Check if an IncomingEntry is a failed (5xx) Request and log that. Useful to log request info with the Exceptions etc.
> Log failed requests

- resources/js/screens/dumps/index.vue
- src/Http/Controllers/DumpController.php
This simplifies the error handler for the Dump messages and brings it in-line with the existing error messages:
> Simplify dump error screen

- src/Telescope.php
(Originally #692)
Resolves #673.
There can now be multiple tag-setting callbacks. This is useful if a package wants to set tags without overriding tags set by the user.
This could be done in v2 in an ugly way:
```php
$originalCallback = Telescope::$tagUsing;
Telescope::tag(function ($entry) use($originalCallback) {
$originalTags = [];
if (! is_null($originalCallback) {
$originalTags = $originalCallback($entry);
} 
$tags = // custom logic
return array_merge($originalTags, $tags);
});
```
And it would work only with two tags, unless all callbacks did this logic.
This PR makes this much nicer.
I would have added tests, but not sure how to do that (related to #691).
> [3.0] Change Telescope::$tagUsing to an array

- phpstan.neon.dist
This pull request deletes `phpstan.neon.dist` as larastan is no longer included.
> Deletes `phpstan.neon.dist` as larastan is no longer included

- config/telescope.php
- resources/js/components/RelatedEntries.vue
- resources/js/routes.js
- resources/js/screens/views/index.vue
- resources/js/screens/views/preview.vue
- resources/views/layout.blade.php
- src/EntryType.php
- src/Http/Controllers/ViewsController.php
- src/Http/routes.php
- src/Telescope.php
- src/Watchers/ViewWatcher.php
This adds a Watcher for the Views/templates. 
The RequestWatcher logs the latest view, but not any other views/subviews which might be useful.
The `extractDataFromView` could be re-used, but I think that would generate a lot of data / cost in CPU.
Icon is the same as Model, not sure where the SVG's are coming from to pick one.
Fixes #677
(Assets are not compiled because of potential merge conflicts)
> Add view collector

- resources/views/layout.blade.php
Adding this meta tag may disavow regular indexing robots (google, yahoo, bing, etc.), to index the contents inside Telescope URLs.
Take into account that this is not a barrier to get access to the Telescope components, but at least may avoid those sensitive sections to get index by mistake (there are some indexed already).
Additionally, adding this to robots.txt may disavow robots for indexing, but will expose your Telescope URL to the public so you may want to avoid this and using this meta tag instead.
> Adding meta for disavowing robots

- resources/js/components/RelatedEntries.vue
This is probably only useful in combinations with 3rd party tools like https://github.com/fruitcake/laravel-telescope-toolbar but let's it jump to the correct tab directly. It also updates the hash (for sharing etc.), without updating the history.
> Jump to related entry by hash

- resources/js/components/RelatedEntries.vue
The tab order was changed here: https://github.com/laravel/telescope/commit/459a11acb5070e649c15059aad67945d6525f622
Which puts the tab before queries, but queries is activated first, so it looks a bit weird that the second tab is activated by default.
> Fix view tab selection order

- composer.json
Due to moontoast/math's use of `ini_set` and `ini_get` on BCMath specific settings a shim cannot be utilized. https://github.com/phpseclib/bcmath_compat/blob/master/README.md elaborates, in the Limitations section.
I've made a pull request to moontoast/math that updates that to make use of bcmath_compat, instead (and rewrites it to avoid the `ini_set` / `ini_get` calls). My PR also fixes compatibility issues that moontoast/math _currently_ has with PHP 7.0+ (PHP 7.0 changed how `bcscale` works and moontoast/math never updated itself accordingly), etc, but at this point, the ball is in their court:
https://github.com/ramsey/moontoast-math/pull/17
If moontoast/math doesn't merge that PR in then maybe it'd make sense for me to create a fork that could live at, say, phpseclib/moontoast-math …
> rm terrafrost/bcmath_compat

- config/telescope.php
- resources/js/components/RelatedEntries.vue
- src/IncomingEntry.php
- src/Watchers/QueryWatcher.php
- tests/Watchers/QueryWatcherTest.php
This formats the SQL in PHP (instead of Javascript) so that they can be shown in the preview window (imho that makes it a lot more clear when looking at them, but might be preference, hence the config options).
It stores the familyHash to be able to check for duplicates (which isn't implemented anywhere yet, but would perhaps be useful).
The view of the Javascript should be the same, with/without pre-formatted SQL.
> Format SQL in watcher

- resources/js/screens/exceptions/index.vue
- resources/js/screens/exceptions/preview.vue
- src/Http/Controllers/ExceptionController.php
- src/Http/routes.php
This allows to mark exceptions as resolved, and show warnings when not resolved.
If an Exception occurs again, it's shown as not-resolved again (because the last entry is shown, which is good).
> Mark exceptions as resolved

- src/ListensForStorageOpportunities.php
- tests/Telescope/TelescopeTest.php
This PR attempts to resolve the bug report made in https://github.com/laravel/telescope/issues/719.
The `storeIfDoneProcessingJob` method already contained a condition for checking if `$connectionName !== 'sync'`, so it seemed reasonable that this condition was also checked when _starting_ recording.
https://github.com/laravel/telescope/blob/fedd672e3c8570e3d4b4e96dd7014a9a7bec8800/src/ListensForStorageOpportunities.php#L86-L89
This fixed the regression test that I added.
> Prevent resuming recording when processing sync job

- src/Watchers/QueryWatcher.php
- tests/Watchers/QueryWatcherTest.php
Checks for `null` values in queryies. Fixes https://github.com/laravel/telescope/issues/726
> Check for null values in query bindings

- resources/views/layout.blade.php
- src/Http/Controllers/HomeController.php
- src/Telescope.php
This adds a check to the base view to show a warning when the manifest file in the public folder is different from the one in the vendor dir. This prevents broken components or missing updates.
The exception is also updated to make it more clear.
Related: #594
> Show warning when manifest is outdated

- resources/js/components/RelatedEntries.vue
This patch is pretty simple. The duration shown on the screen below is wrong because it shows the number of duplicated queries instead of sum of queries duration.
> Use time instead of duplicated to show global queries duration

- src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php
Related to https://github.com/laravel/framework/pull/29983
Migration has `getConnection()` method which used inside of the Migrator class to determine if schema transactions are supported. Without this PR Migrator will check default database connection, but migrations could be executed on custom connection.
> Use getConnection method in Migrations

- src/Telescope.php
- tests/Watchers/RequestWatchersTest.php
Following https://github.com/laravel/telescope/issues/730
"authorization" header is filtered out by default, but it's showing simple HTTP auth server variable "php-auth-pw" where plain password can be seen. This might be a security concern as HTTP auth plain passwords will be stored in DB. I added "php-auth-pw" to $hiddenRequestHeaders to be filtered out by default.
> Hide php-auth-pw server variable by default

- src/Watchers/RequestWatcher.php
- tests/Watchers/RequestWatchersTest.php
In the case the response content-type is plain text (`text/plain`), the response output of the request details view contains the response content instead of the static content `HTML Response`.
> Add formatted output support for plain text responses

- webpack.mix.js
Hi,
Laravel mix v4.0+ is using terser js, it is instructed to update the config, see release docs
https://github.com/JeffreyWay/laravel-mix/releases?after=v4.0.6
> Update webpack config to use terser

- src/Telescope.php
Hello, 
Would you be open to by default ignoring the nova API by default? You can do this individually by project via the config file but the Horizon API is ignored by default so I figured it's worth asking.
The Nova API creates a lot of requests that don't provide much value (in my case), if others get value from those request logs then disregard.
Cheers, Wyatt!
> Add the Nova API to ignore paths array

- resources/js/components/RelatedEntries.vue
- src/Watchers/QueryWatcher.php
Setting the familyHash had the unintended side-effect of grouping the Query entries on the Index page (not on the related pages). This keeps the logic, but uses a property in the `content`, instead of `familyHash`.
The method is kept because of strict BC compatibility (it's public, so technically breaking to rename). But I can change it if you want.
Fixes https://github.com/laravel/telescope/issues/603#issuecomment-535840401
This needs a rebuild for production.
> [2.x] Don't use familyHash for queries

- src/Watchers/NotificationWatcher.php
- tests/Watchers/NotificationWatcherTest.php
When sending an anonymous notification with a string route, The entries are logged successfully. But when using an array of routes, There is an array to string conversion exception in the notification watcher.
```
// This works well
Notification::route('mail', 'telescope@laravel.com')->notify( new SomeNotification() );
```
```
// This throws an array to string conversion exception
Notification::route('mail', ['telescope@laravel.com'])->notify( new SomeNotification() );
```
I have added a test case which verifies working of the new change with array routes.
This is my first time contributing to an open source project. Please guide me in the right direction if i did not follow any standards.
> Properly Implode Nested(Array) Notification Routes To Fix Array To String Conversion Exception

- src/Watchers/RedisWatcher.php
This fixes the case where a redis connection is already set before calling Redis::enableEvents() in a service provider and also doesn't require people to add Redis::enableEvents() manually.
> Enable redis events by default if the watcher is enabled

- resources/js/components/RelatedEntries.vue
Round the queries duration to 2 decimal places.
> [2.x] Fix Round queries duration to 2 decimal places

- src/Watchers/ViewWatcher.php
- tests/Watchers/ViewWatcherTest.php
This fixes #793 which would throw a ReflectionException when a non-closure listener is attached to the `composing: ...`, `creating: ...` or `*` event. 
This happens when a listener is attached like: `Event::listen('*', 'MyListener@handle')`
All view composers/creators are wrapped in a closure, see: `Illuminate\View\Concerns\ManagesEvents@addViewEvent`. That means that we can filter out all listeners that are not a closure when fetching the view composers. 
Technically it would be possible though to create a view composer like `Event::listen('composing: layouts.master', 'MyListener@compose')`. But since there is a dedicated `View::composer` method I assume that's the prefered and supported way to register view composers? If we would add support for those non-closure listeners that would …
> [2.x] Fix ignore generic listeners as view composer

- config/telescope.php
- src/Telescope.php
Make ignoring Laravel Nova paths configurable so Nova apps are debuggable.
Moved 'nova-api*' path from Telescope.php (vendor folder) to telescope.php (user config). This will allow Nova users like me to debug & profile their app via Telescope.
> Make ignoring Laravel Nova paths configurable so Nova apps are debuggable

- src/Telescope.php
Sometimes guard is created when session not initialized yet.
> [2.x] Avoiding to create guard

- src/Watchers/ExceptionWatcher.php
The Stacktrace contains a lot of data sometimes, especially in the `args` part of the Trace. As far as I can tell, these values are not actually used, only `file` and `line` are rendered.
This commit filters the stacktrace to reduce the size of the entries. I've encountered some issues with larger datasets that surpassed the max_allowed_packer from MySQL and thus crashing (the already crashed) app.
> [2.x] Only log file/line for exception trace

- stubs/TelescopeServiceProvider.stub
Follow-up to #821
The SP now uses methods available on the abstract, and not just the concrete Application implementation.
> [2.x] Use environment() instead of isLocal()

- src/Watchers/ViewWatcher.php
I'm not familiar enough to know if there would be any further implications here, though given that a string is expected I can't imagine so... This resolves #824 and all existing tests are still passing.
> fix: ReflectionException when used with debugbar.

- src/ExceptionContext.php
- tests/Watchers/ExceptionWatcherTest.php
With Laravel Telescope and Laravel Tinker enabled in a project, `php artisan tinker` and attempt an expression that _fatally_ fails PHP parsing.
Instead of:
```php
$foo[] = 'bar'`
```
Try typing:
```
foo[] = 'bar'
```
The desired output would be the below exception about the `foo` symbol missing `$`.
> In ExecutionLoopClosure.php(55) : eval()'d code line 1:
> 
> Cannot use temporary expression in write context
Instead the developer is shown an unrelated Laravel Telescope-related stacktrace:
> PHP Warning:  file_get_contents(/home/dev/project/vendor/psy/psysh/src/ExecutionLoopClosure.php(55) : eval()'d code): failed to open stream: No such file or directory in
/home/dev/project/vendor/laravel/telescope/src/ExceptionContext.php on line 45
because the watched `$exception->getFile()` is a …
> [2.x] Handle all eval() failures from Laravel Tinker

- src/IncomingEntry.php
I've added a simple isQuery() function to the IncomingEntry class, in order to log all database queries in addition to the default (non-local env) checks in the Telescope filter:
- isReportableException()
- isFailedRequest()
- isFailedJob()
- isScheduledTask()
- hasMonitorTag()
> improvement - Added isQuery() in IncomingEntry

- .github/workflows/tests.yml
- composer.json
- resources/js/base.js
So we can finally get rid of the warnings in Composer.
Closes https://github.com/laravel/telescope/issues/815
> [4.x] Drop Laravel 6 support and replace moontoast/math

- composer.json
This dependency isn't actually needed and will come with ramsey/uuid v4
> [4.x] Remove brick math

- resources/js/base.js
- src/Telescope.php
- src/Watchers/QueryWatcher.php
This PR provides some fixes when running Telescope during testing.
For example, it's not always certain that the debug backtrace will send back a result so we should check for a value before recording it.
And Telescope should be disabled when a test is faking events since Telescope heavily relies on the usage of events.
Fixes https://github.com/laravel/telescope/issues/573
> [3.x] Testing fixes

- src/Watchers/RedisWatcher.php
Fixes an issue where the RedisWatcher crashed if it tried to log commands which have an array as value. It now properly formats the array to a string using `json_encode`:
Fixes https://github.com/laravel/telescope/issues/845
> [3.x] Encode array for logging

- src/ExtractTags.php
- src/FormatModel.php
Telescope Version: v3.1
Laravel Version: 6.18.0
PHP Version: 7.4.5
---
This PR solves the issue #781. This bug is still happening.
Note:
- The value resolution function has been extracted in a dedicated method for better readability.
- Some code credits also go to @golonix.
> [3.x] Fix typed properties issues

- src/Watchers/QueryWatcher.php
- src/Watchers/RedisWatcher.php
This overrides the default thousands separator in the PHP `number_format` function used to format the time entries. This allows requests that take over 1s/1000ms to be summed up correctly.
For a query with a running time of 1.2s, the current time entry in the database will be `1,200.00`. When this is passed to `parseFloat` in the front end it will be parsed as `1`.
With the change, the value will be stored as `1200.00` and correctly parsed as `1200`.
> [3.x] Remove thousands separator in time records (#876)

- resources/js/screens/logs/index.vue
This should fit better on screen and fix Issue #886 which I reported.
As shown in the screenshot below, this alters the layout slightly when something goes to the 75 chars set on the `truncate` method.
> [3.x] changed truncate from 75 chars to 50

- src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php
When the `telescope_entries` table gets very large, `telescope:prune` will fail miserably, actually bringing an AWS db instance to its knees. This is because `telescope:prune` is using `created_at` in a where clause when there's no index on that column.
> [3.x] Add index to created_at

- config/telescope.php
- package.json
- resources/js/components/PreviewScreen.vue
- src/Avatar.php
- src/EntryResult.php
- src/Http/Controllers/EntryController.php
- src/Telescope.php
- stubs/TelescopeServiceProvider.stub
- tests/Http/AvatarTest.php
Covers: https://github.com/laravel/telescope/issues/742
✔️ Apps can disable Gravatar and stop telling its parent Automattic about user activity on /telescope requests.
✔️ Existing apps still use Gravatar when the new `config('telescope.avatar_driver')` key is not defined so this a non-breaking change for a point release.
✔️ Apps can now show local avatars taken from your own image hosting rather than using a remote service.
```php
namespace App\Providers;
// ...
class TelescopeServiceProvider extends TelescopeApplicationServiceProvider
{
public function register()
{
// ...
Telescope::avatar(function ($id) {
$user = User::find($id);
return url("/assets/images/users/{$user->avatar_path}");
});
}
// ...
}
```
`config('telescope.avatar_driver')` options:
1. `'gravatar'` is the default
2. …
> [3.x] Allow avatar path customization

- src/Telescope.php
As stated in https://github.com/laravel/telescope/pull/867
The entry is not always available in the queue, because it's not always recorded (due to filters).
When adding it as a new param, it shouldn't break BC and you can access the Entry.
> [3.x] Add entry to afterRecording hook

- src/Telescope.php
- tests/Telescope/TelescopeTest.php
Add a hook for after the actual recording. This could be used for notifications etc, sending the actual Telescope URL in the mail/Slack message
```php
Telescope::afterStore(function(Telescope $telescope, $batchId) {
foreach ($telescope::$entriesQueue as $entry) {
if ($entry instanceof IncomingExceptionEntry) {
dispatch(new TelescopeExceptionNotification($entry));
}
}
});
```
> [3.x] Add afterStore hooks

- resources/js/screens/exceptions/preview.vue
Following up on pull request #710. I think although exceptions are marked as resolved the message isn't clear to the user. For once I thought Laravel Telescope would itself 'automagically' resolve the exception for me since that's what the message suggested (Resolve now). This change is to indicate to users that exceptions aren't resolved by Laravel Telescope but marked as resolved, so they have to go resolve the exception themselves and mark as resolved on Laravel Telescope which is the intention of pull request #710
> [3.x] Change text for Marking Exceptions as Resolved

- resources/sass/app-dark.scss
- resources/sass/app.scss
On a network/browser that blocks Google Fonts (for any reason), custom base font `Nunito` will fail to load and the dashboard may end up looking ugly. Screesnhot:
With the fallback to `sans-serif`:
> [3.x] Add explicit base font family fallback

- resources/js/screens/queries/preview.vue
Fixes: https://github.com/laravel/telescope/issues/919
Replaces pull request https://github.com/laravel/telescope/pull/923 as per [Dries' request](https://github.com/laravel/telescope/pull/923#discussion_r461064565)
Formatted SQL preview:
which should be:
Telescope's `QueryWatcher` always stores an empty array for query parameter bindings.
https://github.com/laravel/telescope/blob/f5dee9aa18f4ec426130676bd1e50dac79ec91e4/src/Watchers/QueryWatcher.php#L39-L41
This causes an issue in NPM package `sql-formatter` when the query has MySQL session variables referenced with an `'@'` character. Using the generic SQL:2011 dialect, it's treated like a named placeholder (e.g., for MS SQL Server.)
```javascript
sqlFormatter.format('select @user_id := id as id from users', {params: []});
// select
// …
```
> [3.x] Remove problematic unused code when formatting SQL

- src/Watchers/LogWatcher.php
why ?
```
$th = new \Exception("test string log");
\Log::error($th);
```
This code can normally write to the laravel journal file.
But logs in telepope are null
> fix:May be written to an empty log

- README.md
This PR depends on the following PR to be merged first:
https://github.com/laravel/laravel.com-next/pull/128
> [3.x] Fix non-active cloudinary links

- tests/Telescope/TelescopeTest.php
- tests/Watchers/MailWatcherTest.php
- tests/Watchers/NotificationWatcherTest.php
- Using the `assertFale` to assert expected and result are `false`.
- Using the `assertCount` to assert result length is same as expected count.
> Improve assertions

- src/Watchers/EventWatcher.php
- tests/Watchers/EventWatcherTest.php
Fixes https://github.com/laravel/telescope/issues/952
> [4.x] Make event watcher compatible with Laravel 8 subscriber syntax

- resources/js/screens/dumps/index.vue
- resources/js/screens/dumps/sfdump.js
This PR hooks up the var dumper JS so that the toggles and search work.
Implements #636 
The most valuable part of this IMO is that if you dump an object, your page isn't full of completely expanded objects. (Try dumping `app()` a couple of times 😅 ) It's more consistent with what you'd see if you weren't using Telescope.
Since Vue can't execute JS that's sent from the server and injected through `v-html`, I've had to basically copy paste [the var dumper JS](https://github.com/symfony/symfony/blob/5.1/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php#L163-L656).
There's only a handful of modifications:
- Instead of `Sfdump = window.Sfdump || (function (doc) {`, I'm putting the function into a `this.sfDump` property on the Vue instance.
- The quotes …
> [4.x] Dump visibility toggling, search, etc.

- config/telescope.php
- src/Telescope.php
Non-breaking changes. 
Only start recording on the given paths **if any are specified**
Reason: It is a hassel if you only want to monitor a single path.
Example: Great for only monitoring api requests in production eg.:
```
'only_allow_paths' => [
'api/*'
],
```
If none are specified then it falls back to checking ignore_paths which is still the default.
> Feature: Be able to specify only allowed paths

- src/IncomingEntry.php
This will allow us to filter the entries of type 'request' in the register method in TelescopeServiceProvider
> [4.x] Determine if the incoming entry is a request, added isRequest() filter

- .github/workflows/tests.yml
- composer.json
- tests/Watchers/ExceptionWatcherTest.php
> [4.x] Support php8

- src/TelescopeServiceProvider.php
Fix for Can't locate path: <.../vendor/laravel/telescope/src/Storage/migrations>
Hit the same problem as laravel/telescope#978
I've manually fixed my side but thought it might help to do a pull request to hopefully save you guys some work.
> [4.x] Fix for Can't locate path: <.../vendor/laravel/telescope/src/Storage/migrations>

- src/Storage/DatabaseEntriesRepository.php
Hello, while clearing the db tables the `delete` statement being used is significantly slower than `truncate`. 
The logs the `delete` keeps are useless since these tables contain only debugging info and not essential data.
While using `telescope:clear` it takes very much time for several million records whilst manually executing `truncate` takes a couple of seconds for about the same amount of records. Also it consumes fewer server resources. I think the statement should be changed from `delete` to `truncate`.
[Truncate Statement](https://dev.mysql.com/doc/refman/8.0/en/truncate-table.html)
[Truncate vs Delete](https://stackoverflow.com/questions/20559893/comparison-of-truncate-vs-delete-in-mysql-sqlserver)
> [4.x] Updated db command for clearing tables

- config/telescope.php
- resources/js/mixins/entriesStyles.js
- resources/js/screens/models/preview.vue
- src/Watchers/ModelWatcher.php
- tests/FeatureTestCase.php
- tests/Watchers/ModelWatcherTest.php
Re-attempt of https://github.com/laravel/telescope/pull/999 without a separate tab or watcher.
This PR adds the ability to record model hydrations within the Model Watcher (without a separate tab or watcher). This would help to know how many models are being hydrated for a request - something that can have a significant on performance / memory usage. Inspired from a similar popular feature of Debugbar: barryvdh/laravel-debugbar#947.
There are no breaking changes with this PR. To enable recording of model hydrations, we would need to enable the `hydrations` flag in the `config/telescope.php` file like so:
```php
Watchers\ModelWatcher::class => [
'enabled' => env('TELESCOPE_MODEL_WATCHER', true),
'events' => ['eloquent.*'],
'hydrations' => true,
],
```
This PR would need a re-build and I …
> [4.x] Add model hydrations to model watcher

- src/ExtractProperties.php
> Prevent access to uninitialized typed properties

- src/Watchers/GateWatcher.php
- tests/Watchers/GateWatcherTest.php
While returning and using the `Illuminate\Auth\Access\Response` class deny and allow methods from policies, I noticed that telescope is recording the Gate results as always **allowed**
I determined that the `$result` argument that the `GateWatcher` class is looking at it as only a bool, but this value also has the possibility of being an instance of `Illuminate\Auth\Access\Response` in the case of a policy that is returning a response, so when the policy has `$this->denied('Reason for denial')` the request entry reflects a status code of 403, but it is confusing to see the gate value is allowed.
As the intention of Telescope is to assist in debugging and seeing whats happening, this actually causes confusion in the long run.
The changes I made was to look if the `$result` argument is an …
> [4.x] Fix: GateWatcher shows allowed when it is denied via Response class

- tests/FeatureTestCase.php
- tests/Http/RouteTest.php
Telescope v4 only supports Laravel v8 so these can now be safely removed.
> [4.x] Remove Laravel 7 workarounds

- src/Watchers/JobWatcher.php
- tests/Watchers/JobWatcherTest.php
`BatchRepository::find()` may return `Batch` or `null`. This fixes laravel/nova-issues#3243
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> Handle when $batch is null

- composer.json
- src/Watchers/FetchesStackTrace.php
- src/Watchers/GateWatcher.php
- tests/Watchers/GateWatcherTest.php
This PR implements the new `GateEvaluated` event which will be shipped with tomorrow's Laravel v8.29.0 release. It fixes an issue where Gate `after` checks weren't properly recorded by Telescope.
I had to introduce a breaking change for the `getCallerFromStackTrace` call to allow it to pass the lines that should be forgotten from the stack trace when recording the backtrace. I needed to introduce this because the backtrace is now two lines instead of two. Another option is to put the contents from `recordGateCheck` in `handleGateEvaluated` but that would be an even bigger breaking change I think.
Fixes https://github.com/laravel/telescope/issues/1014
> [4.x] Implement new GateEvaluated event

- src/Watchers/DumpWatcher.php
Move cache read inside VarDumper handler to avoid cache call during package discovery/composer install calls. Fixes #1023.
> [4.x] Move cache read inside handler to avoid early cache call

- src/ListensForStorageOpportunities.php
- src/Telescope.php
- src/Watchers/EventWatcher.php
This allows Telescope to work with Laravel Octane.
> Prep For Octane

- src/TelescopeServiceProvider.php
In some cases you'd always want to boot commands, even if Telescope itself isn't enabled.
> [4.x] Always boot commands

- resources/views/layout.blade.php
- src/Http/Controllers/HomeController.php
- src/Telescope.php
This PR reverts #729, removing the checks to determine at runtime if Telescope's assets are published and up to date.
The exception that is thrown if the assets appear to be missing doesn't play nicely with Vapor because it assumes that the assets should be present on the local filesystem at runtime, and the warning feels unnecessary too since for quite a long time now the docs have had [very clear instructions about how to keep assets up to date automatically](https://laravel.com/docs/8.x/telescope#upgrading-telescope).
Closes #1062.
See also laravel/telescope#594 and laravel/horizon#554, this warning wasn't immediately popular when it was added and both Telescope and Horizon now provide documentation that make it unnecessary.
> Remove asset manifest check and warning

- src/Watchers/QueryWatcher.php
This pull request will solve https://github.com/laravel/telescope/issues/1065.
Note: The fallback method may not constraint with all the target databases that ODBC is connected, It means that there is no way to know which charset, and quote symbol is the default used by the database, however the fallback method should represent an accurate query string for the most popular databases like mSQL, BigQuery or Snowflake.
> [4.x] Implemented fallback for PDO::quote method on QueryWatcher

- resources/js/app.js
- resources/js/components/IndexScreen.vue
- resources/views/layout.blade.php
- src/Http/Controllers/EntriesController.php
- src/Http/routes.php
This pull request adds a new "Clear Entries" button at the top of the layout (after the Pause Recording button).
Clicking it triggers a call the the backend which clears the entries in the database and also wipes the current in-memory entries of the Vue app.
The SVG icon comes from zondicons to match the other telescope icons.
This feature has been touroughly tested and works both when new entries are loaded automatically and when they are not.
Any comments, questions, code review, bugs of missing features would be very welcome.
Personally, as a heavy telescope user, this would be a very welcome feature, and a nice addition to the great tool that telescope is.
When debuging, this new button is much quicker than having to leave your curren window (telescope), go the terminal, call artisan …
> Add a new "Clear Entries" button at the top of Telescope

- src/Watchers/JobWatcher.php
Hey guys. 
I have opened this pr because i encountered a problem when using the JobEncryption feature for a given job.
Telescope assumes the Job is already ready to be unserialized and does not handle encryption
The logic have i stolen from here:
https://github.com/laravel/framework/blob/108385b4f98cacfc1ef1d6e323f57b1c2df3180f/src/Illuminate/Queue/CallQueuedHandler.php#L86-L105
Therefore i have not provided any tests sense the logic is exactly the same apart from the container not being present on the instance itself.
> Added a fix for JobWatchers when the job payload is encrypted

- src/Telescope.php
`Telescope:withoutRecording()` is not exception safe: the original state will not be restored if the exception is thrown in the callback. This PR make `Telescope:withoutRecording()`  exception safe.
> [4.x] `Telescope:withoutRecording()` should be exception safe

- src/Watchers/RequestWatcher.php
While using Telescope Toolbar I noticed that I couldn't view some of the profiles, so upon checking the request response on the Telescope dashboard it said `Purged By Telescope`.
I set `TELESCOPE_RESPONSE_SIZE_LIMIT` to some something really big and was still getting the same behavior. With some debugging I discovered that the check `mb_strlen($content) / 1000` was giving a float as the result rather than an int.
Setting `TELESCOPE_RESPONSE_SIZE_LIMIT` to a float fixed the issue, however, I don't imagine this is the expected behavior. As such we can fix this issue by using the `intdiv` function.
> Use intdiv where appropriate to prevent unexpected conversion to float.

- src/TelescopeServiceProvider.php
Hi! I think we still need publishing even while the module is disabled.
> Fix publishing for disabled module

- src/Watchers/ClientRequestWatcher.php
When response is recorded it sets the response stream to eof and when trying to access the contents of the stream you get an empty string.
This PR rewinds the stream to beginning after copying the content of the response.
To reproduce
```
$response = Http::get('https://httpbin.org/get');
echo $response->toPsrResponse()->getBody()->getContents();
```
> [4.x] Rewind http client response after recording

- src/Watchers/FetchesStackTrace.php
- src/Watchers/GateWatcher.php
Fixes https://github.com/laravel/telescope/issues/1072 & https://github.com/laravel/telescope/issues/1122
TLDR: `GateWatcher` throws an exception because it can't find the PHP source code location that triggered a gate check for an app using Swoole/Laravel Octane.
With `config('telescope.watchers.Watchers\GateWatcher.ignore_packages')` enabled (the default setting), method `getCallerFromStackTrace()` returns `null` because only vendor/laravel/* code is traced through and no app/Http/Controllers/*.php file is reached. Middleware `vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php` triggered the gate check and `GateWatcher@recordGateCheck()` throws an exception attempting to save the Telescope entry for a missing file location. …
> [4.x] Laravel Octane fix: GateWatcher handles stack trace caller not found

- src/Telescope.php
Fixes https://github.com/laravel/telescope/issues/1126 introduced by https://github.com/laravel/telescope/pull/1124
Taylor rightly questioned [why the domain check was an OR conditional](https://github.com/laravel/telescope/pull/1123#discussion_r705621841) as that ended up breaking Telescope's behavior using the out-of-the-box config:
```php
return [
'domain' => env('TELESCOPE_DOMAIN', null),
'path' => env('TELESCOPE_PATH', 'telescope'), // e.g., https://example.com/telescope
// ...
];
```
With Telescope's default `config('telescope.domain') === null`, the new method `requestIsToApprovedDomain()` was always returning true. This skips `requestIsToApprovedUri()` and permits every path to be logged. Telescope database entries are being inserted for /telescope/requests, /telescope/batches, …
> [4.x] Don't log HTTP requests to Telescope endpoints

- resources/js/screens/mail/index.vue
We have notifications that are sent using solely `bcc` recipients in our app and this causes the `Mail` resource to load infinitely.
This change accounts for the fact that `entry.content.to` can be null for a valid mailable.
Related #851.
> Fix mail to check to allow for null `to` fields

- .gitattributes
- package-lock.json
- package.json
- resources/js/components/ExceptionCodePreview.vue
- resources/js/screens/queries/preview.vue
- resources/sass/base.scss
- resources/sass/syntaxhighlight.scss
- webpack.mix.js
This PR fixes the syntax highlighting issues on the queries and the exceptions.
The syntax highlighting on the SQL code wasn't working at all:
There was no syntax highlighting on the exception code preview:
I've updated highlight.js from 10.x to 11.x and added some css classes.
Also, I've reduced the bundle size by updating an outdated webpack configuration.
The `webpack.IgnorePlugin` has changed its syntax since it was added in 2018.
So now the bundle is reduced from **1128kb** to **894kb**!
See: https://webpack.js.org/plugins/ignore-plugin/#example-of-ignoring-moment-locales
I will also submit a PR in Horizon which uses the same configuration for webpack.IgnorePlugin.
> Fix syntax highlighting

- config/telescope.php
- src/Watchers/RequestWatcher.php
Hello folks, add support ignore request when status code specified
> Add support ignore request when status code specified

- src/ExtractsMailableTags.php
Hi! :wave: 
In a project I manage, in which we use Telescope, we also have set up functionality to record any sent emails in the database using the `Illuminate\Mail\Mailable::buildViewDataUsing()` callback to pass the payload to the `MessageSending` or `MessageSent` events.
When we have Telescope enabled, we find that this functionality breaks. This is because when Telescope starts it registers its own data to build up views with, and therefore overwrites our mailable data. For reference, this is where we define our own mailable data: https://github.com/bristol-su/portal-mail/blob/develop/src/MailServiceProvider.php#L89
This PR retrieves the current callback during the `start` function, and then if it isn't empty calls it when building View data and merges the result with Telescopes view …
> Merge previously defined view data when building the view mailable data

- src/Storage/DatabaseEntriesRepository.php
If users have set retrieval of results from the database query builder to array hydration, the content parameter of an Telescope entry will be an array instead of an object. Therefor we'll need to fallback to an array if the parameter isn't an object.
Fixes #1164
> [4.x] Fix issue with array hydration

- src/Watchers/ModelWatcher.php
This is an attempt to fix https://github.com/laravel/telescope/issues/1081 & https://github.com/laravel/telescope/issues/1068.
https://github.com/laravel/telescope/pull/1000 introduced the ability to record how many hydrations of a specific model occurred. This however, does not seem to function properly on Vapor specifically. [It was originally also post-reported on the related PR](https://github.com/laravel/telescope/pull/1000#discussion_r559066549) but given the nature of it being Vapor specific it was very hard to reproduce for the OP.
My analysis leads me to believe that the saving of the incoming entry occurs and then afterwards, for some reason unknown, Telescope still attempts to hydrate a model when being run on Vapor. Because [the incoming entry's `content` has already been json …
> [4.x] Attempt to fix model hydration

- src/Watchers/ModelWatcher.php
It seems a breakage snuck in with my previous PR: https://github.com/laravel/telescope/pull/1174. Because the payload is decoded as an associative array (as should because we can't guarantee the data order in the payload), when new events happen with this payload we'll need to reference the named key instead. 
It's beyond me why new events are recorded but I guess this can happen since every eloquent model event is being watched. 
Fixes https://github.com/laravel/telescope/issues/1178
> [4.x] Fix key handling for ModelWatcher

- .github/workflows/update-changelog.yml
Use the target branch of a release in the compare URL when updating the changelog through GitHub Actions.
> [4.x] Use release target branch in changelog compare URL

- .github/workflows/tests.yml
- composer.json
- src/Watchers/MailWatcher.php
- tests/Watchers/MailNotificationTest.php
As described in #1186, mail displays sent through the Notification classes are not displayed correctly.
Upon further investigation, I was able to find out that the HTML is not correctly split/parsed from the e-mail envelope containing headers, a raw/markdown representation of the notification and lastly, the HTML representation.
<details>
<summary>This is that e-mail envelope (taken from the debugger):</summary>
```
--1l2lTBZn
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
[Laravel](http://localhost)
The introduction to the noti=
fication.
Notification Action: http://localhost
Thank you for usi=
ng our application!
Regards,
Laravel
If you're having trouble c=
licking the "Notification Action" button, copy and paste the URL below
in=
to your web …
```
> [4.x] Mails sent through Notifications preview invalid HTML

- resources/js/screens/requests/index.vue
This fixes an issue where the requests table was overflowing when the url path is too long. We can solve this simply by truncating the url a bit more.
Fixes #1193
> [2.x] Truncate request url more

- config/telescope.php
- src/Watchers/DumpWatcher.php
This PR adds an environment variable (`TELESCOPE_DUMP_WATCHER_ALWAYS`) to let the user decide if Telescope should record dumps even if the dump watcher tab is closed.
I always expect my dumps to be recorded by Telescope and every time I forget to keep the dump watcher tab open, it throws me off. Here is a non-breaking solution to that.
> Add option to record dumps even though the dump watcher tab is not open

- src/IncomingExceptionEntry.php
- src/Telescope.php
- src/Watchers/ExceptionWatcher.php
- src/Watchers/LogWatcher.php
- tests/Watchers/ExceptionWatcherTest.php
This will enable any Throwable, such as a PHP Error, to be picked up by Telescope and show up under the Exceptions tab.
> Use Throwable instead of Exception

- src/Watchers/CacheWatcher.php
- tests/Watchers/CacheWatcherTest.php
When using telescope, I ran into a problem that cache values were too big to store (`SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes`). I do not need to know the value, but I do want to know the event happened. This feature allows to hide the value, based on the key and allowing wildcards.
> CacheWatcher hide values

- src/Telescope.php
This is a small change that modifies https://github.com/laravel/telescope/pull/200 slightly by reading the Horizon path (if one is set / exists) when ignoring requests coming from Horizon, rather than hardcoding the default `horizon/*` path.
> Read from Horizon config when ignoring requests

- src/Watchers/GateWatcher.php
The current `Watchers\GateWatcher` class expects to receive an optional Authenticatable value in place of the `$user` variable. This causes an exception to be thrown if you define gates against non-Authenticatable objects.
Gates can be defined against any object/model and may not be a user, even if this is the most common use case.
For example, in my app, I use a feature flag library that registers features as gates against an Organization model, where you can then do something like `$organization->can('v2.0')`.
The interface of the laravel `Gate` class specifies that it can be an Authenticatable or **mixed** parameter:
```
/**
* Get a guard instance for the given user.
*
* @param  \Illuminate\Contracts\Auth\Authenticatable|mixed  $user
* @return static
*/
public function forUser($user); …
```
> Relax user type in GateWatcher to match Laravel base framework.

- config/telescope.php
- src/Watchers/RequestWatcher.php
Added the ability to disable request recording to `Watchers\RequestWatcher::class` by HTTP verb method.
I often have a situation where I need to turn off the preflight `OPTIONS` requests  recording or record only `GET` requests, so that it doesn't get distracting.
> Add support for ignoring by HTTP Verb

- src/Telescope.php
At now, while u add tags in `register` method `TelescopeServiceProvider.php`, like:
```
Telescope::tag(function (IncomingEntry $entry) {
$result = [];
if ($entry->type === EntryType::CLIENT_REQUEST) {
$result[] = 'http';
$result[] = 'http:' . $entry->content['response_status'];
if ($entry->content['response_status'] >= 400) {
$result[] = 'failed';
}
}
return $result;
});
```
u cant use `$entry->user`. its always `null`. 
This PR move parsing-tags-code after set-user-code.
> Check tags after set $this->user()

- src/Watchers/ClientRequestWatcher.php
- src/Watchers/RequestWatcher.php
Hello,
I'm using Telescope to watch incoming request & outgoing request. 
I was wondering if possible to distinguish a HTML Response with content vs an empty HTML Response.
What you think ?
> RequestWatcher & ClientRequestWatcher : HTML Response vs Empty Response

- src/Watchers/JobWatcher.php
This PR prevents Telescope from recording duplicate queries when unserializing a job. Ideally the duplicate queries shouldn't happen but at least this prevents duplicate date from being added to Telescope.
Fixes https://github.com/laravel/telescope/issues/1255
> [4.x] Do not record when unserializing command

- src/Watchers/JobWatcher.php
Small adjustment for my PR at https://github.com/laravel/telescope/pull/1257. We should check if Telescope was recording to begin with. If it wasn't, we should also not re-enable recording.
> [4.x] Fix re-enabling recording

- src/Watchers/RedisWatcher.php
- tests/Watchers/RedisWatcherTest.php
When installing Telescope into a Laravel application which has opted out of Redis support by removing the `RedisServiceProvider` in `app.php`, a `BindingResolutionException` is thrown during auto-discovery:
```sh
⇒  composer require --dev laravel/telescope
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^4.9 for laravel/telescope
./composer.json has been updated
Running composer update laravel/telescope
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
- Locking laravel/telescope (v4.9.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
- Downloading laravel/telescope (v4.9.4)
- Installing …
```
> Dont register redis watcher if the redis service is not bound into the container.

- src/Storage/DatabaseEntriesRepository.php
I have encountered an issue, where the telescope did not save any requests for me.
**Example of issue**:
Send a request to the application with telescope enabled: `/?my-parameter=4jOH%1a%14)%1a7%d1%60%8cd%40t%94%86m%e6%f8`
**The expected result**: Request to be logged (if so configured) in the telescope.
**Actual result**: Nothing is saved (as if no request was sent)
**Cause**:
json_encode in some situations fails to encode binary data, silently fails, and returns false.
**Possible abuse**:
This can also be abused and requests which are generated for malicious purposes could be hidden from the telescope simply by including a bit of binary data which fails to json_encode.
**Solution**:
We can tell json_encode to replace invalid utf8 characters to \0xfffd. Which corrupts the original …
> Fix issue where json_encode quietly fails due to binary data inside telescope entry

- config/telescope.php
- src/Watchers/FetchesStackTrace.php
**Problem**
The "file" portion of the Query Watcher is unhelpful if you extend certain classes (e.g. `MySqlConnection.php`) since that adds a persistent layer to the stack trace.
**Solution**
One easy fix for this is to allow folks to specify any extra files they want excluded from the stack trace like so:
```sql
Watchers\QueryWatcher::class => [
'enabled' => env('TELESCOPE_QUERY_WATCHER', true),
'ignore_packages' => true,
'ignore_paths' => ['MySqlConnection.php'],
'slow' => 100,
]
```
_(which fixes the above problem)_
**Where are the tests?**
`tests/Watchers/QueryWatcherTest.php` doesn't try testing `'file'` and there isn't a test file for `FetchesStackTrace.php`. I'm happy to take a go at adding some upon request if this solution seems acceptable. If not, let me know what solution you …
> Add the Ability to Pass Custom `ignore_paths` To Query Watcher

- resources/js/components/RelatedEntries.vue
adjust text-break layout with text-break class
In the case of very long text, the layout was breaking with this adjustment, it automatically fixes it, I increased it to 200 characters as well.
>  adjust text-break layout with text-break class

- src/FormatModel.php
As the title states, add support for model keys cast to backed enums in FormatModel. I have not scouted the whole codebase, there may be other places where a fix is needed to support backed enums for model keys.
I came across this bug while working on a project of mine. I had left this project alone for a couple of weeks before resuming it today. The issue didn't happen before, and I did a `composer update` when resuming, so this might be a  regression. I, unfortunately, do not have the time to check more thoroughly.
Hope this helps. Thank you.
> Add support for model keys cast to backed enums in FormatModel

- src/Telescope.php
- src/Watchers/DumpWatcher.php
Fixes issue #620
When trying to `composer install` locally with the redis cache driver configured, if redis is unreachable the following error occurs:
```
php_network_getaddresses: getaddrinfo for redis failed: nodename nor servname provided, or not known
at [internal]:0
1▕ 
+24 vendor frames 
25  [internal]:0
Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Laravel\Telescope\TelescopeServiceProvider))
+5 vendor frames 
31  artisan:35
Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```
This PR fixes the issue by handling the occurred exception and …
> [4.x] Handle redis connection exception on DumpWatcher register

- resources/views/layout.blade.php
The header button icons are slightly lower than center. This PR addresses that.
Due to some CSS weird stuff, the buttons are now slightly less square now. It could be addressed with some custom css, but:
1. I don't think it looks bad
2. The buttons were not square in the first place.
> [4.x] Center header button icons

- database/migrations/2018_08_08_100000_create_telescope_entries_table.php
After https://github.com/laravel/framework/pull/46073, this pull request resolves the migration issue in Telescope by utilizing lazy instantiation to create the schema, similar to how regular migrations function.
> [4.x] Creates a fresh instance of schema for each migration

- src/Watchers/JobWatcher.php
@taylorotwell: As promised: this exact change in Telescope prevents a memory leak (causing models to be retained) when running the `scout:import` command w/ Laravel Scout. 
This happened in our case when the models being bulk imported are rather large and logging in Telescope is on. At that point, importing more than a 10k model entries simply ends the import as PHP runs out of memory. If the job is not recorded, this issue does not occur.
For anyone else reading, please take a look at the discussion in https://github.com/laravel/scout/pull/703 where I explain in more detail what happened in our use case.
> Prevent `Laravel\Scout\Jobs\MakeSearchable` job from being recorded to avoid memory leak

- config/telescope.php
- src/Watchers/LogWatcher.php
- tests/Watchers/LogWatcherTest.php
This merge request adds the `level` option to the `LogWatcher` in Telescope. The default value of the `level` option is debug, for backward compatibility. However, after merging this request, users will begin to use the updated configuration stub with error as the default log level.
It's important to note that regular deprecations are considered as warnings. Therefore, users will only see the deprecations in their telescope table if they set the log level to `warning` or lower.
One thing, up to debate, is that whether the `LOG_LEVEL` environment variable should be utilized in the config/telescope.php stub.
> [4.x] Allows to specify the log level

- .gitattributes
- .github/workflows/static-analysis.yml
- composer.json
- phpstan.neon.dist
- src/Telescope.php
This pull request adds type checking to this project.
Note: I've removed code from `src/Telescope.php` as the class `FatalThrowableError` does not exists in Laravel 8, Laravel 9 or Laravel 10.
> [4.x] Adds type checking

- src/Telescope.php
This PR allows method Telescope::withoutRecording to return output of the passed callable method thus allowing to make cleaner code & more in line with what is already used for database transactions in Eloquent.
I came accross this when trying to disable telescope logging on one particular command.
**Before:**
```php
Telescope::stopRecording();
if(/* Some condition */)
Telescope::startRecording();
return self::SUCCESS;
}
Telescope::startRecording();
return self::FAILURE;
```
**After:**
```php
return Telescope::withoutRecording(function() {
if(/* Some condition */)
return self::SUCCESS;
}
return self::FAILURE;
});
```
> Return callable output on Telescope::withoutRecording

- src/Console/PauseCommand.php
- src/Console/ResumeCommand.php
When using a custom cache driver that depends on runtime context, this causes `php artisan package:discover` to fail as that context is not available, when it would be when `handle()` injection is performed.
Other telescope commands are using `handle()` injection aswell so this makes it more consistent throughout.
> [4.x] Don't use constructor injection in console commands, and inject into handle() instead

- src/Contracts/EntriesRepository.php
- src/Jobs/ProcessPendingUpdates.php
- src/Storage/DatabaseEntriesRepository.php
- src/Telescope.php
- src/Watchers/JobWatcher.php
- tests/Jobs/ProcessPendingUpdatesTest.php
- tests/Storage/DatabaseEntriesRepositoryTest.php
This pull request fixes the "pending" job status (https://github.com/laravel/telescope/issues/1331, https://github.com/laravel/telescope/issues/1113, https://github.com/laravel/telescope/issues/577, https://github.com/laravel/telescope/issues/507, https://github.com/laravel/telescope/issues/543, https://github.com/laravel/telescope/issues/690, https://github.com/laravel/telescope/issues/503, https://github.com/laravel/telescope/issues/411), by simply delaying the "failed" updates to performed a few seconds after via queued job.
> [4.x] Fixes jobs saying "pending" forever

- src/Telescope.php
This PR aims to prevent a memory leak when we call the method `hideRequestHeaders` or/and `hideRequestParameters` multiple times with the same parameters. Ex:
```php
Telescope::hideRequestHeaders(['cookie', 'x-csrf-token']);
Telescope::hideRequestHeaders(['cookie', 'x-csrf-token']);
```
It seems like an inoffensive issue, but it causes a memory leak in tests:
```php
class MemoryLeakTest extends TestCaseUnit
{
public function test_leaks_memory_on_1000_iterations()
{
$this->app->flush();
$this->app = null;
for ($i = 1; $i < 500; ++$i) {
$this->createApplication()
->flush();
if (! ($i % 10)) {
dump('Using ' . ((int) (memory_get_usage(true) / (1024 * 1024))) . 'MB as ' . $i . ' iterations.');
}
}
$this->app = $this->createApplication();
}
}
```
> The code above was copied from …
> Prevent Memory Leak when using hideRequestParameters and hideRequestHeaders

- src/Watchers/JobWatcher.php
- tests/Watchers/JobWatcherTest.php
- tests/Watchers/NotificationWatcherTest.php
This pull request addresses the problem described in issue https://github.com/laravel/telescope/issues/1353. Currently, when a job fails, we attempt to queue an "update" for the failed job status through ProcessPendingUpdates even before it exists in Telescope. However, there is an issue with this approach. The update may include a stack trace that contains references to closures, which, as we are aware, cannot be serialized.
Note that, the arguments are not even used on the Telescope UI, so we can remove them safely.
> [4.x] Avoids serialialisation of exception traces

- src/Watchers/ClientRequestWatcher.php
- src/Watchers/RequestWatcher.php
- tests/Watchers/ClientRequestWatcherTest.php
- tests/Watchers/RequestWatchersTest.php
When an array of headers is present, we now show the array rather than only the first value.
Request see "x-foo"
Response see "set-cookie"
Went wit comma separated list instead of an actual array, as it creates consistency between those that already use the comma as a list mechanism and those that do not.
> [4.x] Show list of headers when present

- src/Telescope.php
Due to the nature of Laravel Vapor, which often processes jobs more quickly than the HTTP response, there is a small likelihood of this change dispatching more jobs than a regular server. Therefore, it would be better to disable this feature on Vapor.
> [4.x] Fixes unexpected jobs on Vapor

- tests/FeatureTestCase.php
also exclude all other packages.
> Test Improvements

- package.json
I installed Telescope on one of the laravel projects I was working on and while watching for activities in Telescope web app I found out that the committed time of the app activities (cache, queries, requests, etc.) in the list is the wrong time for Asia/Tehran timezone.
Tehran used to have a daylight saving time. After returning to the standard time on 22 September 2022, the Iran Government elected to remain permanently in the standard time, cancelling daylight saving time. Hence, Iran will permanently remain at UTC +3:30 time zone going forward.
Moment.js uses a dependancy moment-timezone to convert time based on the custom timezone not the browser's Intl obejct. so that's why we need to update this dependancy in package.json
I checked the records in database saved in …
> modified moment-timezone package version in package.json

- resources/js/components/RelatedEntries.vue
Fixes duplicated query count when running same sql statement on multiple connections.
> Fix duplicated queries on multiple connections

- config/telescope.php
Ignore pulse and livewire by default
> Ignore pulse and livewire

- .github/workflows/tests.yml
- UPGRADE.md
- composer.json
- src/Console/InstallCommand.php
- src/Telescope.php
- src/TelescopeServiceProvider.php
- testbench.yaml
- tests/FeatureTestCase.php
- tests/Http/AuthorizationTest.php
- tests/Http/AvatarTest.php
- tests/Http/RouteTest.php
- tests/Watchers/BatchWatcherTest.php
- tests/Watchers/EventWatcherTest.php
- tests/Watchers/GateWatcherTest.php
- tests/Watchers/JobWatcherTest.php
- tests/Watchers/LogWatcherTest.php
- tests/Watchers/ModelWatcherTest.php
- workbench/database/seeders/DatabaseSeeder.php
This pull request adds Laravel 11 support to Telescope.
> [5.x] Adds Laravel 11 support

- src/Storage/DatabaseEntriesRepository.php
I couldn't immediately figure out why this happens but sometimes Telescopes seems to attempt to insert an entry tag for a uuid and tag combo which already exists. I figured just ignoring the exception here is the best way to handle this as having the entry in the database is what's important.
This problem started to arise after we added the primary key: https://github.com/laravel/telescope/pull/1425. That's a good thing though, since this probably was happening before and filling the database table with duplicate entries, which it now won't anymore.
Fixes https://github.com/laravel/telescope/issues/1430
> [4.x] Ignore duplicate tags

- stubs/TelescopeServiceProvider.stub
I came across this bug when running the Dusk test suite in a new project with Telescope installed. (Local dev environment running on macOS using sail)
Accessing `$this` inside the closure results in the following error: `Target class [env] does not exist.`
This can be fixed by calculating whether the environment is `local` before the filter colsure and passing the value in.
Full error log:
```
FAIL  Tests\Browser\RegistrationTest
✓ register valid user                                                                                  2.58s
⨯ register password mismatch
────────────────────────────────────────────────────────────────────────────────────────────────────────────
FAILED  Tests\Browser\RegistrationTest > register password mismatch             BindingResolutionException
Target …
```
> [4.x] Add `use` to closure to pass in environment condition

- config/telescope.php
> ignore laravel boost routes
