laravel/telescope

src/ExtractProperties.php
src/ExtractTags.php
src/Watchers/EventWatcher.php

[1.0] add @throws tags

---

src/Http/Controllers/MonitoredTagController.php

[1.0] use fully qualified class name

---

webpack.mix.js

Let's pull some configs from [horizon](https://github.com/laravel/horizon/blob/1.0/webpack.mix.js) repo.
1. reduce bundle size by ignoring moment.js locales
2. drop console.log calls from code

Update mix configs

---

resources/js/components/IndexScreen.vue
resources/js/components/PreviewScreen.vue
resources/js/screens/monitoring/index.vue

helps with viewing on smaller devices

[1.0] make tables responsive

---

src/EntryType.php

[1.0] Order constants

---

src/EntryResult.php
src/Telescope.php
src/Watchers/EventWatcher.php
src/Watchers/ExceptionWatcher.php
src/Watchers/JobWatcher.php
src/Watchers/QueryWatcher.php
src/Watchers/RedisWatcher.php

Fix param docblocks (FQN) and use consistent spacing

[1.0] Fix param docblocks (FQN) and use consistant spacing

---

src/Http/Controllers/DumpController.php

`put` is a repository function, not a factory function.

[1.0] Use cache repository

---

src/Http/Controllers/DumpController.php

[1.0] Fix controller docblock.

---

src/Console/InstallCommand.php
src/ExtractTags.php
src/Watchers/LogWatcher.php

Prefer direct calls to `Arr` and `Str` classes

[1.0] Prefer direct calls to Arr and Str classes

---

src/Watchers/LogWatcher.php

[1.0] Remove whitespacy line

---

src/EntryUpdate.php
src/IncomingDumpEntry.php
src/IncomingEntry.php

[1.0] Remove useless brackets.

---

src/Http/Controllers/MailEmlController.php
src/Http/Controllers/MailHtmlController.php

[1.0] Remove useless imports.

---

readme.md

[1.0] Add syntax highlighting

---

resources/js/components/IndexScreen.vue
resources/js/components/PreviewScreen.vue
resources/js/mixins/entriesStyles.js
resources/js/screens/monitoring/index.vue

Replaced
== and != 
with
=== and !==

Enforce === and !==

---

config/telescope.php

Added missing comma to the config file

Added missing comma

---

src/Telescope.php
tests/FeatureTestCase.php
tests/Watchers/QueryWatcherTest.php
tests/Watchers/RequestWatchersTest.php

- Feature Test to cover `password` and `password_confirmation` fields being blurred;
- Feature Test to cover database queries being logged;
- Feature Test to cover slow queries being properly tagged.

[Test Coverage] Database Queries and Password Request

---

resources/js/app.js
resources/views/layout.blade.php

Add X-CSRF-TOKEN to every axios request

---

stubs/TelescopeServiceProvider.stub

[1.0] Call isLocal() method on stub for passing larastan checks

---

.gitattributes
.styleci.yml

Add StyleCI check.
---
Closes #119

[1.0] Add StyleCI check.

---

src/ListensForStorageOpportunities.php

[1.0] FIX Avoid jobs recording stop if queue driver is sync

---

.gitattributes

resubmit of https://github.com/laravel/telescope/pull/208

[1.0] Update gitatributes

---

src/Watchers/QueryWatcher.php

fix QueryWatcher stack trace collector for closure

---

composer.json
src/Watchers/EventWatcher.php

Document missing @throws exceptions in EventWatcher

#247: Added missing @throws \ReflectionException in EventWatcher

---

src/Console/PruneCommand.php
src/TelescopeServiceProvider.php

Resubmit of https://github.com/laravel/telescope/pull/261 without conflicts

[1.0] Fix contract

---

config/telescope.php
src/Contracts/EntriesRepository.php
src/Storage/DatabaseEntriesRepository.php
src/Telescope.php

If people want to remove older entries they should use the prune console command or implement their own scheduled job.

Remove trimming of entries

---

tests/Http/RouteTest.php

I don't know how I missed all these routes the first time. Added them now.

[Coverage] Add missing index routes

---

readme.md

Add the build status badge with the 1.0 branch

[1.0] Add build status badge

---

tests/Http/AuthorizationTest.php

After this Pull Request, we'll be at around 74% line of code covered 61% of methods touched and 41% of files. Most of Telescope's core functionality are being covered already, except Tags.

[Coverage] Telescope Auth System

---

tests/Console/ClearCommandTest.php
tests/Storage/DatabaseEntriesRepositoryTest.php
tests/Watchers/CacheWatcherTest.php
tests/Watchers/CommandWatcherTest.php
tests/Watchers/DumpWatcherTest.php
tests/Watchers/EventWatcherTest.php
tests/Watchers/ExceptionWatcherTest.php
tests/Watchers/JobWatcherTest.php
tests/Watchers/LogWatcherTest.php
tests/Watchers/MailWatcherTest.php
tests/Watchers/ModelWatcherTest.php
tests/Watchers/QueryWatcherTest.php
tests/Watchers/RedisWatcherTest.php
tests/Watchers/RequestWatchersTest.php

Use `$this->assert` in place of `self::assert`.
There are no differences in term of performances or assertion.
But the non-static call is more consistent with the tests found in Laravel repositories.

Use `$this->assert`

---

src/Watchers/RequestWatcher.php

this **PR** resolves #342 ,and adds view template details when visiting request details , and this is a screenshot of how it will look like

[1.0] show used blade template details in request detail screen

---

resources/views/layout.blade.php
src/Http/Controllers/HomeController.php

Extract some logic from the layout into the controller.

[1.0] Extract some logic from the layout into the controller.

---

config/telescope.php

As a follow up to #370 and #223, I've taken a stab at adding config options for ignored paths and ignored commands. I've followed the comment convention but I understand that Taylor is very picky on config (and rightly so) :grin: so feel free to close if it doesn't make sense.

[1.0] Add config options for ignored paths and commands

---

src/Http/Controllers/RecordingController.php
src/Storage/factories/EntryModelFactory.php

[1.0] Fix docblocks.

---

src/Console/PruneCommand.php

As per @themsaid's suggestion, now using an optional age parameter on the command to choose the age before pruning.

Adding age parameter to pruning command

---

composer.json
src/ExtractProperties.php
src/ExtractTags.php
src/FormatModel.php
src/Watchers/ModelWatcher.php
src/Watchers/NotificationWatcher.php
src/Watchers/RequestWatcher.php

Using `(array) $model->getKey()` causes issues with UUID (https://github.com/laravel/telescope/issues/353)
`Arr::wrap()` is a better approach

Format model string

---

src/ListensForStorageOpportunities.php
tests/Http/AuthorizationTest.php

[1.0] use strict compare

---

src/Contracts/EntriesRepository.php
src/Storage/DatabaseEntriesRepository.php

- update phpDoc for cases where collection is a collection of one type elements. This improvements will allowed type hinting for the item;)

[1.0] Update phpDoc

---

src/EntryResult.php

Change Carbon type hint to CarbonInterface for CorbonImmutable compatibility.
A possible solution to the problem described in this issue #567

Change Carbon type hint to CarbonInterface

---

CHANGELOG.md

PR creates a changelog for Telescope dating back to v2.0. 
I'll keep this updated periodically for releases.
Closes #625.

[2.0] Add Changelog

---

tests/Watchers/GateWatcherTest.php

There was a line number shift, so the tests did not work

Fix gate tests

---

resources/js/screens/requests/preview.vue
src/Watchers/RequestWatcher.php

Collect memory usage in the current request.
(Assets are not compiled yet)

Add memory to request watcher

---

src/IncomingEntry.php
stubs/TelescopeServiceProvider.stub

Merge failed request PR into 2.0

---

src/Console/InstallCommand.php

Change str_replace_last to Str::replaceLast()

Change str_replace_last to Str::replaceLast()

---

src/IncomingEntry.php

Haven't encountered any issues, but the phpdocs say it's a string, so make sure it's actually a string.

Make sure UUID is string

---

config/telescope.php
src/Watchers/EventWatcher.php
tests/Watchers/EventWatcherTest.php

Sometimes event properties serialization triggered new events(Example: Nova+Field collecting event). 
It would be nice to add the ability to exclude events from collecting.

Added support for event ignoring.

---

resources/js/screens/views/index.vue

Fixes undefined composers key when not available. Introduced with #766

[2.x] Check if composers key exists

---

src/ExtractTags.php

Similar to https://github.com/laravel/horizon/pull/738.

[2.0] Manual code style fixes

---

src/Telescope.php

Fix #838 Array to string conversion

---

src/Console/InstallCommand.php

Preserving the alphabetical order of providers

---

UPGRADE.md

[4.x] Add UPGRADE.md

---

tests/Watchers/BatchWatcherTest.php

Added batch watcher test for #903

[4.x] Add Batch Watcher Test

---

src/Console/PruneCommand.php
src/Contracts/PrunableRepository.php
src/Storage/DatabaseEntriesRepository.php

Takes —keep-exceptions argument

Retain exceptions data

---

src/IncomingEntry.php

Determine if the incoming entry is of type gate

[4.x] Added isGate() filter

---

src/Storage/DatabaseEntriesRepository.php

Revert "[4.x] Updated db command for clearing tables"

---

src/Watchers/RequestWatcher.php

[4.x] Fix typo in memory calculation

---

resources/views/layout.blade.php

Fix spaces

---

src/Watchers/DumpWatcher.php

Reverts laravel/telescope#1025

Revert "[4.x] Move cache read inside handler to avoid early cache call"

---

src/Watchers/ClientRequestWatcher.php
tests/Watchers/ClientRequestWatcherTest.php

Improve file handling in client request watcher

---

src/Contracts/PrunableRepository.php

see implementer: https://github.com/laravel/telescope/blob/4.x/src/Storage/DatabaseEntriesRepository.php#L336

Fix return type

---

resources/js/app.js
resources/views/layout.blade.php
src/Http/Controllers/EntriesController.php
src/Http/routes.php

As discussed in #1087 this is a repackage of the same PR (with @taylorotwell 's modifications) to be merged into the 4.x branch.
I couldn't take My commits and taylor's because taylor's included the compiled assests and I'm not supposed to do it so I'll let you compile them.

Repackaged #1087 for 4.x (Add a new "Clear Entries" button)

---

src/Watchers/ClientRequestWatcher.php

[4.x] Suppress filesize errors in client request watcher

---

src/TelescopeServiceProvider.php

[4.x] Unified asset publishing

---

src/Telescope.php

See laravel/telescope#1123 MR.

[4.x] Fix `telescope.domain` usage.

---

resources/js/components/RelatedEntries.vue
resources/js/screens/client-requests/index.vue
resources/js/screens/client-requests/preview.vue
resources/views/layout.blade.php

Replace Http/Uri with HTTP/URI

---

src/EntryResult.php
src/Watchers/ClientRequestWatcher.php
src/Watchers/RequestWatcher.php

Fix PHP 8.1 issues

---

.github/workflows/tests.yml
composer.json
database/migrations/2018_08_08_100000_create_telescope_entries_table.php
stubs/TelescopeServiceProvider.stub

Please check https://github.com/laravel/laravel/pull/6010 for details about this pull request.

[4.x] Uses PHP Native Type Declarations 🐘 

---

src/Watchers/MailWatcher.php
tests/Watchers/MailWatcherTest.php

Closes https://github.com/laravel/telescope/issues/1339

Fix MailWatcher tags

---

src/Watchers/ClientRequestWatcher.php

Fixes Laravel v9 compatibility.
Fixes https://github.com/laravel/telescope/issues/1359

Fix non existing property

---

src/Storage/DatabaseEntriesRepository.php

Clear all entries from tables using chunks
Fix Issue [#1410](https://github.com/laravel/telescope/issues/1410)

fix: clear all entries using chunks

---

.github/workflows/tests.yml

Waiting for: https://github.com/laravel/octane/pull/753.

[4.x] Adds PHP 8.3 testing

---

database/migrations/2018_08_08_100000_create_telescope_entries_table.php

Resend of https://github.com/laravel/telescope/pull/1407

[4.x] Add primary keys to database tables
